### ISSUE TITLE
Add a special case to the inliner for unsafeCoerce?

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript-unsafe-coerce#1]

**Comment by hdgarrood** [comment]
Perhaps this isn't worth doing, as JS engines are hopefully clever enough to figure out that this should be inlined on their own?

**Comment by hdgarrood** [comment]
This is a compiler issue, see purescript/purescript#2572.

**Comment by paf31** [comment]
👍 It seems like this could open up some more interesting optimizations in general.
