### ISSUE TITLE
Move to core?

### ISSUE THREAD

**Issue by garyb** [purescript/purescript-unsafe-coerce#3]
There are places it would be useful, as we could eliminate the need for FFI usage in `exists`, for example. /cc @paf31

**Comment by paf31** [comment]
:+1: if @hdgarrood is ok with it.

**Comment by garyb** [comment]
Oops, of course, sorry @hdgarrood I didn't mean to leave you out of it! :smile:

**Comment by hdgarrood** [comment]
I'm watching anyway :) :+1: from me too.

**Comment by garyb** [comment]
Thanks!
